name: Commit Message Check

on:
  pull_request:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Commit Message Check
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          echo "Checking commit message: $COMMIT_MSG"
          python -c '
          import re, sys
          commit_msg = """'"$COMMIT_MSG"'""".strip()
          if not re.match(r"^(feat|chore):\s[A-Z].+", commit_msg):
              print("ERROR: Commit message must start with feat or chore and follow the format:")
              print("Example: feat: Add new feature")
              sys.exit(1)
          print("Commit message format is correct!")
          '
