name: Commit Message Check

on:
  push:  # Runs on every push to all branches
  pull_request:  # Runs on all pull requests

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is available

      - name: Run Commit Message Check
        run: |
          # Get all commit messages in the push or PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            COMMIT_MSGS=$(git log --format=%B --no-merges ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          else
            COMMIT_MSGS=$(git log --format=%B --no-merges ${{ github.event.before }}..${{ github.event.after }})
          fi

          echo "Checking commit messages..."

          # Iterate over each commit message
          while IFS= read -r commit_msg; do
            commit_msg=$(echo "$commit_msg" | tr -d '\n' | sed 's/ *$//')  # Remove trailing newlines and spaces

            if [[ "$commit_msg" == Merge* ]]; then
              echo "✅ Skipping merge commit: $commit_msg"
              continue
            fi

            if ! echo "$commit_msg" | grep -qE "^(feat|chore):\s[A-Z].+"; then
              echo "❌ ERROR: Invalid commit message format!"
              echo "Commit message: \"$commit_msg\""
              echo "Commit messages must start with \"feat\" or \"chore\" and follow this format:"
              echo "   Example: feat: Add new feature"
              echo "   Example: chore: Update dependencies"
              exit 1
            fi

            echo "✅ Commit message format is correct: \"$commit_msg\""
          done <<< "$COMMIT_MSGS"
