name: Commit Message Check

on:
  pull_request:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Run Commit Message Check
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1)
          echo "Checking commit message: \"$COMMIT_MSG\""
          
          python -c '
          import re, sys
          commit_msg = """'"$COMMIT_MSG"'""".strip()
          if not re.match(r"^(feat|chore):\s[A-Z].+", commit_msg):
              print(commit_msg)
              print("❌ ERROR: Commit message must start with feat or chore and follow the format:")
              print("   Example: feat: Add new feature")
              print("   Example: chore: Update dependencies")
              sys.exit(1)
          
          print("✅ Commit message format is correct!")
          '
