name: Commit Message Check

on:
  pull_request:

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history is available

      - name: Run Commit Message Check
        run: |
          COMMIT_MSG=$(git log --format=%B -n 1)
          echo "Checking commit message: \"$COMMIT_MSG\""

          # Skip merge commits
          if [[ "$COMMIT_MSG" == Merge* ]]; then
            echo "✅ Merge commit detected. Skipping commit message check."
            exit 0
          fi
          
          python -c '
          import re, sys
          commit_msg = """'"$COMMIT_MSG"'""".strip()
          pattern = r"^(feat|chore):\s[A-Z].+"
          
          if not re.match(pattern, commit_msg):
              print("❌ ERROR: Invalid commit message format!")
              print("Commit messages must start with \"feat\" or \"chore\" and follow this format:")
              print("   Example: feat: Add new feature")
              print("   Example: chore: Update dependencies")
              sys.exit(1)
          
          print("✅ Commit message format is correct!")
          '
