name: Commit Message Check

on:
  push:  # Runs on every push to all branches
  pull_request:  # Runs on all pull requests

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is available

      - name: Run Commit Message Check
        run: |
          # Find the last merge commit on main
          LAST_MERGE=$(git merge-base origin/main HEAD)

          # Determine commit range
          if [ -n "$LAST_MERGE" ]; then
            COMMIT_RANGE="$LAST_MERGE..HEAD"
          else
            COMMIT_RANGE="HEAD"  # If no merge found, check the latest commit
          fi

          echo "Checking commit range: $COMMIT_RANGE"

          # Get commit messages from the last merge until now
          COMMIT_MSGS=$(git log --format=%B --no-merges $COMMIT_RANGE)

          echo "Checking commit messages..."
          echo "$COMMIT_MSGS" | while IFS= read -r commit_msg; do
            commit_msg=$(echo "$commit_msg" | tr -d '\n' | sed 's/ *$//')  # Clean up message

            # Skip empty lines
            if [[ -z "$commit_msg" ]]; then
              continue
            fi

            # Skip merge commits
            if [[ "$commit_msg" == Merge* ]]; then
              echo "✅ Skipping merge commit: $commit_msg"
              continue
            fi

            # Validate commit message format
            if ! echo "$commit_msg" | grep -qE "^(feat|chore):\s[A-Z].+"; then
              echo "❌ ERROR: Invalid commit message format!"
              echo "Commit message: \"$commit_msg\""
              echo "Commit messages must start with \"feat\" or \"chore\" and follow this format:"
              echo "   Example: feat: Add new feature"
              echo "   Example: chore: Update dependencies"
              exit 1
            fi

            echo "✅ Commit message format is correct: \"$commit_msg\""
          done
